server:
  port: ${PORT:10101}


eureka:
  client:
    enabled: ${EUREKA_CLIENT_ENABLED:true}
    register-with-eureka: ${EUREKA_CLIENT_REGISTER_WITH_EUREKA:true}
    fetch-registry: ${EUREKA_CLIENT_FETCH_REGISTRY:true}
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:10100/eureka}


spring:
  application:
    name: gateway-service
  web-application-type: reactive
  allow-bean-definition-overriding: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
        - name: Retry
          args:
            retries: 1
            methods: GET,PUT,POST,PATCH,DELETE
            exceptions:
              - reactor.netty.http.client.PrematureCloseException
      httpclient:
        pool:
          max-idle-time: 2000
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns:
              -  "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      routes:
          - id: auth-service
            uri: ${AUTH_SERVICE_URI:lb://auth-service}
            predicates:
              - Path=/auth-service/**  # Auth servis için route
            filters:
              - StripPrefix=1
              - RemoveRequestHeader=Cookie

          - id: user-service
            uri: ${USER_SERVICE_URI:lb://user-service}
            predicates:
              - Path=/user-service/**
            filters:
              - StripPrefix=1
              - RemoveRequestHeader=Cookie
              - AuthenticationFilter
            metadata:
                authorizedRoles.DELETE./api/users/**: "ADMIN"

          - id: product-service
            uri: ${PRODUCT_SERVICE_URI:lb://product-service}
            predicates:
              - Path=/product-service/**
            filters:
              - StripPrefix=1
              - RemoveRequestHeader=Cookie
              - AuthenticationFilter
            metadata:
                authorizedRoles.DELETE./api/products/**: "ADMIN"

          - id: order-service
            uri: ${ORDER_SERVICE_URI:lb://order-service}
            predicates:
              - Path=/order-service/**
            filters:
              - StripPrefix=1
              - RemoveRequestHeader=Cookie
              - AuthenticationFilter
            metadata:
                authorizedRoles.DELETE./api/orders/**: "ADMIN"

          - id: place-service
            uri: ${PLACE_SERVICE_URI:lb://place-service}
            predicates:
              - Path=/place-service/**
            filters:
              - StripPrefix=1
              - RemoveRequestHeader=Cookie
              - AuthenticationFilter
            metadata:
                authorizedRoles.DELETE./api/places/**: "ADMIN"

          - id: music-service
            uri: ${MUSIC_SERVICE_URI:lb://music-service}
            predicates:
              - Path=/music-service/**
            filters:
              - StripPrefix=1
              - RemoveRequestHeader=Cookie
              - AuthenticationFilter

# Application Security Configuration
application:
  security:
    jwt:
      secret-key: "hJOaQpw7GkGBXiJZVx3jFABCDEFGH1234567890abcdefghijklmnopqrstuvwxyz=="
      expiration: 86400000
      refresh-token:
        expiration: 604800000
