server:
  port: 10101


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:10100/eureka


spring:
  application:
    name: gateway-service
  web-application-type: reactive
  allow-bean-definition-overriding: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
        - name: Retry
          args:
            retries: 1
            methods: GET,PUT,POST,DELETE
            exceptions:
              - reactor.netty.http.client.PrematureCloseException
      httpclient:
        pool:
          max-idle-time: 2000
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns:
              -  "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      routes:
          - id: auth-service
            uri: lb://auth-service  # Load balancer üzerinden
            predicates:
              - Path=/auth-service/**  # Auth servis için route
            filters:
              - StripPrefix=1
              - RemoveRequestHeader=Cookie

          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=/user-service/**
            filters:
              - StripPrefix=1
              - RemoveRequestHeader=Cookie
              - AuthenticationFilter
            metadata:
                authorizedRoles.DELETE./api/users/**: "ADMIN"

          - id: product-service
            uri: lb://product-service
            predicates:
              - Path=/product-service/**
            filters:
              - StripPrefix=1
              - RemoveRequestHeader=Cookie
              - AuthenticationFilter
            metadata:
                authorizedRoles.DELETE./api/products/**: "ADMIN"

          - id: order-service
            uri: lb://order-service
            predicates:
              - Path=/order-service/**
            filters:
              - StripPrefix=1
              - RemoveRequestHeader=Cookie
              - AuthenticationFilter
            metadata:
                authorizedRoles.DELETE./api/orders/**: "ADMIN"

# Application Security Configuration
application:
  security:
    jwt:
      secret-key: "hJOaQpw7GkGBXiJZVx3jFABCDEFGH1234567890abcdefghijklmnopqrstuvwxyz=="
      expiration: 86400000
      refresh-token:
        expiration: 604800000
