server.port=10112

spring.application.name=place-service

eureka.client.service-url.defaultZone=http://localhost:10100/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.datasource.url=${PLACE_DB_URL:jdbc:h2:mem:placedb;MODE=MSSQLServer;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.username=${PLACE_DB_USERNAME:sa}
spring.datasource.password=${PLACE_DB_PASSWORD:}
spring.datasource.driver-class-name=${PLACE_DB_DRIVER:org.h2.Driver}

# Spring JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=${PLACE_DB_DIALECT:org.hibernate.dialect.H2Dialect}
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
